version: '2'

services:
  proxy:
    image: traefik
    command: --web --docker --docker.watch --docker.domain=localhost --logLevel=DEBUG --entryPoints="Name:http Address::80"
    networks:
      - redzilla
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  #  This used to work
  # test2:
  #   image: nodered/node-red-docker
  #   container_name: test2
  #   networks:
  #     - redzilla
  #   volumes:
  #     - ./data/instances/test2:/data
  #   labels:
  #     - "traefik.backend=test2"
  #     - "traefik.port=1880"
  #     - "traefik.frontend.entryPoints=http"

networks:
  redzilla:
    driver: bridge
